apiVersion: apps/v1
kind: Deployment

metadata:
  name: my-application
  labels:
    app: my-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-application
  template:
    metadata:
      labels:
        app: my-application
    spec:
      containers:
        - name: my-app-container
          image: vijaydocker1812/dockerimagepr:latest
          ports:
            - containerPort: 8081